export const db = {
  loginDoms: [
    {
      url: 'https://id.nikkei.com/lounge/nl/auth/bpgw/LA0310.seam',
      name: 'Nikkei X tech',
      idFormId: 'LA0310Form01:LA0310Email',
      idFormClass: null,
      idFormClassOrder: null,
      idFormName: 'LA0310Form01:LA0310Email',
      idFormType: null,
      pwFormId: 'LA0310Form01:LA0310Password',
      pwFormClass: null,
      pwFormClassOrder: null,
      pwFormName: 'LA0310Form01:LA0310Password',
      pwFormType: 'password',
    },
    {
      url: 'https://id.nikkei.com/lounge/nl/connect/page/LA7010.seam',
      name: '日経 電子版',
      idFormId: 'LA7010Form01:LA7010Email',
      idFormClass: null,
      idFormClassOrder: null,
      idFormName: 'LA7010Form01:LA7010Email',
      idFormType: null,
      pwFormId: 'LA7010Form01:LA7010Password',
      pwFormClass: null,
      pwFormClassOrder: null,
      pwFormName: 'LA7010Form01:LA7010Password',
      pwFormType: 'password',
    },
  ],
  credentials: [
    {
      id: '1',
      extensionUserID: 'test1',
      url: 'https://id.nikkei.com/lounge/nl/auth/bpgw/LA0310.seam',
      userID: 'testuser1',
      userPW: 'testpw1',
    },
    {
      id: '2',
      extensionUserID: 'test2',
      url: 'https://id.nikkei.com/lounge/nl/auth/bpgw/LA0310.seam',
      userID: 'testuser2',
      userPW: 'testpw2',
    },
  ],
};
